-- begin CONTOSO_ENROLLMENT
alter table CONTOSO_ENROLLMENT add constraint FK_CONTOSO_ENROLLMENT_COURSE foreign key (COURSE_ID) references CONTOSO_COURSE(ID)^
alter table CONTOSO_ENROLLMENT add constraint FK_CONTOSO_ENROLLMENT_STUDENT foreign key (STUDENT_ID) references CONTOSO_STUDENT_(ID)^
create index IDX_CONTOSO_ENROLLMENT_COURSE on CONTOSO_ENROLLMENT (COURSE_ID)^
create index IDX_CONTOSO_ENROLLMENT_STUDENT on CONTOSO_ENROLLMENT (STUDENT_ID)^
-- end CONTOSO_ENROLLMENT
